### PR TITLE
Create bundle_pt_BR.properties

### PR DESCRIPTION
**Pull request by RayanZ22**
Brazillian Portuguese Translation

### CODE REVIEW

**Comment by Mesokrix** [comment]
Bundle is alway good idea

**Comment by Mesokrix** [comment]
Just say me when its finish and i add it

**Comment by RayanZ22** [comment]
OK dude


Em sáb, 19 de set de 2020 12:37, Mesokrix <notifications@github.com>
escreveu:

**Comment by RayanZ22** [comment]
yea it's okay.

**Comment by Mesokrix** [comment]
ok, I merge it so

**Pull request merged**
