### PR TITLE
fix grammatical errors in readme

### PR DESCRIPTION
**Pull request by markozajc**
don't use google translate next time

### CODE REVIEW

**Comment by Pekka-Angelo** [comment]
But if we suck in English 😅

**Review by Pekka-Angelo — APPROVED** [review]
Thank you for correcting the syntax errors and correcting the translation errors 👍

**Comment by markozajc** [comment]
that's assuming I'll even create a second pr

**Comment by Mesokrix** [comment]
that I will surely refuse

**Comment by markozajc** [comment]
how does one refuse a pr

**Pull request closed without merging**
